### ISSUE TITLE
Transaction can be signed more than once without changing votes number

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/snt-voting#36]
One transaction can be signed a lot of times when voting in a poll

#### Expected behavior:
Sign transaction view should not be available

#### Actual behavior:
It's possible to proceed and sign a transaction again

#### Steps to reproduce:
- Open a poll
- Vote
- Sign transaction
- Close the browser
- Swipe and delete the browser entity
- Open the poll again
- Without changing number of votes proceed to the Sign transaction screen

**Comment by Graeme-Code** [comment]
Hi @yevh-berdnyk we made a UX decision to allow user to always be able to tap vote button even if they have not changed their votes. This was because users were tapping back from review votes back and then been unable to go forward unless they change votes. 

Note that signing multiple transactions will not create multiple votes, each signing of a transaction will update the accounts vote. 

I'm closing the issue.
